### ISSUE TITLE
Post links directly to Linklet.ml, build voting system to upvote useful resources

### ISSUE THREAD

**Issue by duttakapil** [vinaypuppal/linklet-app#1]
Here's an idea, what if rather than taking the links from our WhatsApp group, our community members can directly share/post links on linklet.ml?
We could also implement some voting system, so you can upvote links you find really helpful. We can have labels to filter between different domains and make the process of searching resources much easier. 

If you think this is a good idea, thumb's up this issue and/or write your feedback in the comments below

**Comment by duttakapil** [comment]
We need more people to vote on this. Or else just get started with it anyway

**Comment by duttakapil** [comment]
I think just being able to post links directly to the site would be enough for now, as it would make it more automatic, and the entire community can view it

**Comment by vinaypuppal** [comment]
closing this as we implemented posting links directly to the site
