### ISSUE TITLE
It will be more usable if the windows open faster in the mobile app.

### ISSUE THREAD

**Issue by Kamalnrf** [vinaypuppal/linklet-app#12]
When I'm moving between screens the app takes time in loading that page which is unusable sometimes...

**Comment by vinaypuppal** [comment]
@Kamalnrf can you provide these details
- Which browser are you using, 
- your network speed

~~My tests indicate each page loads usually in 10s from INDIA using 2G connection [check here](https://www.webpagetest.org/video/view.php?id=170420_74_13CN.1.0). So on high speed connections it should load under 3 to 5 seconds.
**Are you experiencing more than 10s load time?**~~

**Comment by vinaypuppal** [comment]
Hey I was able to reproduce this issue, on site added to home screen and only on 2G connection. This is what I noticed
- Open app
- After page loaded immediately click on `My Links` or `Submit Link` or `Profile` tab buttons/links
- There is no loading indicator at top and but after some time clicked pages are loaded
- And if we navigate b/w screens 2 times and from 3rd time the loading indicator is showing up
@Kamalnrf  **So is this what you are experiencing right??**

So I investigated why this is happening what I found is for the first 2 times the `app.js` file which contains event listeners to show loading indicator is not yet loaded as it is loaded asynchronously so so when we click the tab button 3rd or 4th time by that time it was loaded so loading indicator is showing up. 
I think you caught up in this scenario few times as clicking on tab button provides no visual feedback but navigates to that page, so you thought it was slow I guess.

*It was reported by few others in `Next.js` repo https://github.com/zeit/next.js/issues/1630*

I tried to bring down load time  by adding `app.js` to cache(so on next visits it will load from cache) and lazy loaded user profile images(before these were blocking loading of `app.js`) but still its happening few times on very slow connection. And i have no idea how to solve this yet 😟

**Comment by vinaypuppal** [comment]
For now i added this temporary fix which will indicate users that site is still loading

![screen shot 2017-04-21 at 7 04 56 am](https://cloud.githubusercontent.com/assets/8843216/25259375/5e9265d2-2663-11e7-812a-4d0195eef72c.png)

**Comment by vinaypuppal** [comment]
@Kamalnrf Closing this since I upgraded linklet-app to [next@2.3.0](https://github.com/zeit/next.js/releases/tag/2.3.0) and these changes will give apps a significant page load speed over version 2.0 of Next.js and also it has better caching support.
