### ISSUE TITLE
Provide a way to categorize links based on topic 

### ISSUE THREAD

**Issue by hvsharma** [vinaypuppal/linklet-app#2]
Currently the filters are based on date and date range. We need filters and categorization according to the topics..

**Comment by vinaypuppal** [comment]
@hvsharma Thanks for the suggestions, sure I will be implementing them this weekend along with some features which are suggested in #1 also.

**Comment by vinaypuppal** [comment]
@hvsharma linklet now has around 1100 links from WhatsApp so how can we categorize these links automatically?? To some extent we can do based on url for eg: all medium.com links we can add them to articles category but what about rest?? Should we do it manually, I was stumbled upon these questions when I was thinking last night. Do you have any ideas 

cc @duttakapil

**Comment by duttakapil** [comment]
@vinaypuppal we will have to do it manually. This feature is part of the suggestion I made in #1, so we can add labels and the labels can function as categories. We should build it in a wiki way, giving the entire community the power to add, edit and remove labels. That way, when they come across a link on Linklet, they can quickly add a label that fits the link.  

We also will have to delete/remove quite a few links. Let's do a call about this soon and figure it out

**Comment by hvsharma** [comment]
@vinaypuppal @duttakapil As Kapil said.. Categorization definitely have to be manual because links generally don't convey the exact gist of the content. Later we can figure out automatic categorization using some advanced code.. but for now normal manual categorization is fine. Just a simple Label will do. We have to finalize the labels for all the categories.. For example -:

- General Development
- Language Specific
   - JavaScript
      - General
      - Frameworks
         - React
         - Angular ...etc
   - Go
   - Java
   - C#
   - Ruby


I mean we have to create a format for proper categorization first instead of making blind labels. Have to be brainstormed and double checked so that no re-visiting is required later.

**Comment by vinaypuppal** [comment]
@duttakapil Today I was able to compose the most frequent words from links meta data which we can use  to `tag/label` links.
Here is the list https://gist.github.com/vinaypuppal/1409b9acc7d933156644501cd79c0df5
- it contain around 4k words
- many are useless although I applied many filters(able to reduce from actual 7k to 4k words) so we need to further filter them manually
- I sorted them based on the `count `(i.e number of times the word appeared).

I think we can use these tags to categorize as @hvsharma  suggested

P.S Thanks to @afridishayc for the idea and helping me in making this list.

**Comment by duttakapil** [comment]
Interesting. I'm not sure how the output will look like yet, will have to try it out and see. Cutting down from 4K seems harder than coming up with our own small set of labels though

**Comment by vinaypuppal** [comment]
@hvsharma Is the search functionality enough for filtering links based on topic?? Or do we still need filtering based on categories??

**Comment by duttakapil** [comment]
Search will be a good next step, definitely

**Comment by vinaypuppal** [comment]
@duttakapil You did not check whatsapp group??
I implemented search functionality check here https://linklet.ml

**Comment by duttakapil** [comment]
Ya just saw after posting that, awesome progress :D

**Comment by vinaypuppal** [comment]
closing this as we have search bar for filtering resources based on keyword. If you still feel we need categories filter reopen this.
