### ISSUE TITLE
Permission Issue on Push Notifications

### ISSUE THREAD

**Issue by harishkotra** [vinaypuppal/linklet-app#4]
When I toggle ON on push notifications, it didn't show up permissions but turned it on for me. I disabled it and then it asked me for permission. 

Moto G5 Plus
Firefox Browser
![tmp_12665-screenshot_20170417-09493935958231](https://cloud.githubusercontent.com/assets/4999463/25078728/7fda5db6-2353-11e7-8733-89d684537d4e.png)

**Comment by vinaypuppal** [comment]
@harishkotra It seems to work fine on my device's firefox. The toggle logic should not trigger without asking for permissions, i even rechecked the code it seems fine.
I guess it should happen only if service worker registration failed.

**Comment by vinaypuppal** [comment]
@harishkotra Found the issue and fixed it 🎉 
Recheck and if still happens let me know.
Actually what happened is on firefox we need to handle push subscription differently than chrome which caused this issue.
