### ISSUE TITLE
Unexpected error occurs when website opens

### ISSUE THREAD

**Issue by M-ZubairAhmed** [vinaypuppal/linklet-app#6]
Just recently website seems to show error stating "An unexpected error has occurred" when opened

**Comment by vinaypuppal** [comment]
Can you check if there are any errors in browser console if it's desktop browser. If it's mobile browser can you clear cache and try again. Do same if no errors for desktop also.

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed I was able to reproduce this. Fixing and deploying new version now

**Comment by vinaypuppal** [comment]
@M-ZubairAhmed Its Fixed, try it and let me know

**Comment by M-ZubairAhmed** [comment]
Yes, now it works
