### ISSUE TITLE
Unable to submit pdf link

### ISSUE THREAD

**Issue by duttakapil** [vinaypuppal/linklet-app#8]
![image](https://cloud.githubusercontent.com/assets/6577624/25109868/8bdb99b8-23fd-11e7-9fbb-af15095b039d.png)

I was unable to submit [this pdf file](https://dl.dropboxusercontent.com/u/18065445/web2py/web2py_manual_5th.pdf) to the website

Browser : Firefox

**Comment by vinaypuppal** [comment]
Oh yes if the link cannot be scraped for metadata then we cannot add it to linklet because thats not link and its file see .pdf at end of link so metadata cannot be extracted. And without metadata link is not searchable in searchbar.

**Comment by vinaypuppal** [comment]
@duttakapil can i close this issue or do you have any suggestions ?

**Comment by duttakapil** [comment]
Yes go ahead
